version: "3"

services:
  database:
    image: "postgres:latest"
    ports:
      - 15432:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  strapi:
    container_name: strapi
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_USERNAME: ${POSTGRES_USERNAME}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - 1337:1337
    networks:
      - postgres-network
    depends_on:
      - database

networks:
  postgres-network:
    driver: bridge
